package conformance_test

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite REPORT.md")

// TestReport checks that REPORT.md is what the cases declare. It reads
// only the declarations, since TestConformance is what holds each case to
// its state.
func TestReport(t *testing.T) {
	got := report()
	if *update {
		if err := os.WriteFile("REPORT.md", []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile("REPORT.md")
	if err != nil {
		t.Fatal(err)
	}
	if string(want) != got {
		t.Errorf("REPORT.md is stale; run: go test ./conformance -run Report -update")
	}
}

func report() string {
	var b strings.Builder
	b.WriteString("# Conformance report\n\n")
	b.WriteString("Generated by `go test ./conformance -run Report -update`; do not edit.\n\n")
	b.WriteString("Each cell counts a tool's conformant cases against all its cases for\n")
	b.WriteString("the feature.\n\n")

	b.WriteString("| Feature |")
	for _, tool := range tools {
		fmt.Fprintf(&b, " %s |", tool)
	}
	b.WriteString("\n| --- |")
	for range tools {
		b.WriteString(" --- |")
	}
	b.WriteString("\n")
	for _, f := range features {
		fmt.Fprintf(&b, "| [%s](#%s) |", f.Slug, f.Slug)
		for _, tool := range tools {
			var conformant, total int
			for _, c := range f.Cases {
				if c.tool() != tool {
					continue
				}
				total++
				if c.State == Conformant {
					conformant++
				}
			}
			if total == 0 {
				b.WriteString(" |")
				continue
			}
			fmt.Fprintf(&b, " %d/%d |", conformant, total)
		}
		b.WriteString("\n")
	}

	for _, f := range features {
		fmt.Fprintf(&b, "\n## %s\n\n%s\n\n", f.Slug, f.Summary)
		b.WriteString("| State | Command line | Depends on |\n| --- | --- | --- |\n")
		for _, c := range f.Cases {
			fmt.Fprintf(&b, "| %s | `%s` | %s |\n", c.State, c.Argv, strings.Join(c.DependsOn, ", "))
		}
	}
	return b.String()
}
